# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pycqa/flake8
    rev: '4.0.1'
    hooks:
    -   id: flake8
        # stages: [push]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.942'
    hooks:
    -   id: mypy
        pass_filenames: false  # suppress the normal filename passing
        files: ^freqtrade/  # filter the files down to a specific subdirectory
        # pre-commit only supports running at the root of a repo since that's where
        # git hooks run.  but it also allows running arbitrary code so you can
        # step outside of those bounds
        # note that `bash` will reduce your portability slightly
        verbose: true
        entry: mypy freqtrade
        additional_dependencies: 
        -    types-cachetools==5.0.0
        -    types-filelock==3.2.5
        -    types-python-dateutil==2.8.10
        -    types-requests==2.27.15
        -    types-tabulate==0.8.6
        -    types-urllib3==1.26.11

    # and then repeat ...
    -   id: mypy
        pass_filenames: false
        files: ^scripts/
        entry: mypy scripts
        additional_dependencies: 
        -    types-cachetools==5.0.0
        -    types-filelock==3.2.5
        -    types-python-dateutil==2.8.10
        -    types-requests==2.27.15
        -    types-tabulate==0.8.6
        -    types-urllib3==1.26.11


-   repo: https://github.com/pycqa/isort
    rev: '5.10.1'
    hooks:
      - id: isort
        name: isort (python)
        # stages: [push]
