name: Pre-commit auto-update

on:
  # every day at midnight
  schedule:
    - cron: "0 3 * * 2"
  # on demand
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run auto-update
        run: pre-commit autoupdate

      - name: Run pre-commit
        run: pre-commit run --all-files

      - uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          add-paths: .pre-commit-config.yaml
          branch: update/pre-commit-hooks
          title: Update pre-commit hooks
          labels: |
            Tech maintenance
          commit-message: "chore: update pre-commit hooks"
          body: Update versions of pre-commit hooks to latest version.
